alphagov/pay-products

.gitignore, LICENSE, README.md, docs/api_specification.md
1. Added a LICENSE, .gitignore files
2. Updated README to denote the potential initial API's of pay-apps.
=> PP-2566 Adding initial documentation

docker-startup.sh, manifest.yml, src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/resources/HealthCheckResource.java
- enabled healthcheck resource on main port
- the response of it now returns only 200 OK.
- all healthcheck results are logged.
=> PP-2586 made healthcheck public

env.sh, pom.xml, src/main/resources/config/config.yaml
=> PP-2586 Fix few issues in skeleton service

src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java, src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/java/uk/gov/pay/products/service/LinksDecorator.java, src/main/java/uk/gov/pay/products/service/ProductFinder.java, src/main/java/uk/gov/pay/products/util/ProductStatus.java, src/main/resources/migrations/00001_add_catalogues_table.sql, src/main/resources/migrations/00002_add_products_table.sql, src/main/resources/migrations/00003_create_catalogues_external_service_id_idx.sql, src/main/resources/migrations/00004_create_products_status_idx.sql, src/test/java/uk/gov/pay/products/fixtures/CatalogueEntityFixture.java, src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoTest.java, src/test/java/uk/gov/pay/products/resources/ProductsResourceTest.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- Added resource to GET a list of Product by a
query param externalServiceId;
- Added tests to test endpoint returning 200 and a list of existing
products, 404 when no products are found and 401 when not authenticated;
- Changed tests to allow adding Product and Catalogue in separate
operations;
- Updated LinksDecorator to decorate a list of products;
=> PP-2670 Get a list of Products by externalServiceId

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/config/ProductsModule.java, src/main/java/uk/gov/pay/products/filters/LoggingFilter.java, src/main/java/uk/gov/pay/products/healthchecks/DatabaseHealthCheck.java, src/main/java/uk/gov/pay/products/model/Payment.java, src/main/java/uk/gov/pay/products/persistence/dao/PaymentDao.java, src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java, src/main/java/uk/gov/pay/products/persistence/entity/AbstractEntity.java, src/main/java/uk/gov/pay/products/persistence/entity/PaymentEntity.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/main/java/uk/gov/pay/products/resources/PaymentResource.java, src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/java/uk/gov/pay/products/service/LinksDecorator.java, src/main/java/uk/gov/pay/products/service/PaymentFinder.java, src/main/java/uk/gov/pay/products/service/PaymentsFactory.java, src/main/java/uk/gov/pay/products/service/ProductFinder.java, src/main/java/uk/gov/pay/products/util/PaymentStatus.java, src/main/resources/migrations/00009_add_payments_table.sql, src/test/java/uk/gov/pay/products/fixtures/PaymentEntityFixture.java, src/test/java/uk/gov/pay/products/infra/PostgresContainer.java, src/test/java/uk/gov/pay/products/persistence/dao/PaymentDaoTest.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoTest.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java, src/test/java/uk/gov/pay/products/resources/ProductsResourceTest.java, src/test/java/uk/gov/pay/products/service/PaymentFinderTest.java, src/test/java/uk/gov/pay/products/service/ProductsCreatorTest.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
Implemented endpoint to retrieve a specific payment by payment's external id or retrieve a list of payments by the a product's external id
Added table 'payments' create
Added PaymentEntity to reflect the table
Added Payment model
Added PaymentStatus enum
Added PaymentDao
Added endpoints /v1/api/payments/{paymentId} and /v1/api/products/{productId}/payments
Added relevant tests
Updated documents (README and API specification)
Fixed typo in config.yaml
Cleaned up existing code
Refactored DAOs to return entities
=> PP-2672 Implemented GET endpoints

src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- add 'return_url' to the list of mandatory fields in ProductRequestValidator
- add ProductRequestValidator unit tests
- update tests accordingly
=> PP-2672 Add return_url to ProductRequestValidator

pom.xml, src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java, src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/main/java/uk/gov/pay/products/validations/RequestValidations.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/products/client/publicapi/PublicApiRestClientTest.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java, src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStubExpectation.java, src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java, src/test/resources/config/test-it-config.yaml
- Update RequestValidations to check whether the return URL is a valid url
- Make return_url non compulsory
- Add handling of return url. When return url is not present (prototype case) then we add a pre-defined return url
=> Pp 2672 Check valid  and handle return url

src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
Quick bug fix to return an empty list when no product is found instead of 404 as per conventions.
=> PP-2672 Fix to return an empty list when no product is found instead of 404

src/main/java/uk/gov/pay/products/service/PaymentFinder.java, src/test/java/uk/gov/pay/products/service/PaymentFinderTest.java
- refactor findByProductExternalId to query publicapi for charge status if payment status is SUBMITTED
- refactor tests accordingly
=> PP-2672 Refactoring PaymentFinder.findByProductExternalId

src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/main/java/uk/gov/pay/products/validations/RequestValidations.java, src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- Adding max-price validator to reject amounts greater than £10mill mirroring connector
=> PP-2446 Add max price validator

src/main/java/uk/gov/pay/products/util/RandomIdGenerator.java, src/test/java/uk/gov/pay/products/util/RandomIdGeneratorTest.java
Random string generator of length 10
probability set (33 ^ 8) * (8 ^ 2) = 9.0010152e+13 (in the range of 10 - 90^ trillion)
Uses sets of upper case alphabets and numbers (excluding `0`,  `1`, `O`, `I`) with biased on digits on every 3rd and 7th character. 
some .e.g.
```
H1413E7WMU
MD2XJ48XJM
LZ6YNS7SY1
3S8ASF6YE6
6K74276YA4
346HZ53MJL
CR5MNC9M65
ZM1C3K2QU4
9C9FJS7J4D
AS4EU37EYV
```
=> PP-3031 user friendly Random string generator.

src/test/java/uk/gov/pay/products/util/RandomIdGeneratorTest.java
- fix the regex used to test RandomIdGenerator
=> PP-3031 Fix regex test of random reference number

src/main/resources/migrations/00011_add_column_gateway_account_id_to_payments.sql, src/main/resources/migrations/00012_add_column_reference_id_to_payments.sql
- add column gateway_account_id to payments
- add column reference_number to payments
=> PP-3031 Random Reference Number DB changes

src/main/resources/migrations/00014_migrate_gateway_account_id_from_products_to_payments.sql, src/main/resources/migrations/00015_update_non_existestent_reference_ids_in_payments.sql
- migrate gateway_account_id from products to corresponding payments
- back fill reference_number on payments
=> PP-3031 Migrate data to payments

src/main/resources/migrations/00016_set_gateway_account_id_and_reference_number_not_null_on_payments.sql
- Set constraint NOT NULL for gateway_account_id and reference_number on payments
=> PP-3031 Set NOT NULL for gateway_account_id and reference_number

src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java, src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
- Change code to set the new random reference as reference on publicapi PaymentRequest load
=> PP-3031 Set random reference number on PaymentRequest

docs/api_specification.md, src/main/java/uk/gov/pay/products/model/Product.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/main/resources/migrations/00017_add_column_service_name_to_products.sql, src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java, src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- Adds `service_name` column to product in DB (with no constraints for the time being)
- Adds `service_name` to product
- Adds `service_name` as required field when creating a product
=> PP-3035 add service name

src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
Must wait for https://github.com/alphagov/pay-products-ui/pull/42
So that products-ui complete controller to decide where to redirect the user to depending on product type.
=> PP-3036 Making payments to return to products-ui complete URI

src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java, src/main/java/uk/gov/pay/products/service/GatewayAccountUpdater.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoTest.java, src/test/java/uk/gov/pay/products/service/GatewayAccountUpdaterTest.java
- add updateGatewayAccount to ProductDao to perform a batch update
- refactor GatewayAccountUpdater
- refactor/add relevant tests
=> PP-3048 Refactor batch update of Service Name

pom.xml
=> PP-3034 Upgrade dropwizard

README.md, docs/api_specification.md
- update `READ.md` and `api_specification.md` to include the new endpoint
=> PP-3048 Update API documents

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
- removed api token usage from products
- Fixed few readme issues
=> Pp 3204 remove api token

src/main/java/uk/gov/pay/products/validations/RequestValidations.java, src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- fix amount validation (error when amount is above £100.000)
- remove unnecessary test
=> PP-3305 Fix amount validation

pom.xml
- upgrade dropwizard to version 1.2.2
- pin jackson to version 2.9.4
- leave mockito at version at 2.8.47, upgrade would require code changes
=> PP-3336 Upgrade dropwizard to version 1.2.2

src/main/resources/migrations/00020_add_column_friendly_url_name_to_products.sql
- add a new column `friendly-url` to `products` table
=> PP-3308 Add column friendly_url to products table

pom.xml, src/main/resources/migrations/00021_add_unique_constraint_to_friendly_url.sql
- add unique constraint to friendly_url on products table
- remove duplicate pom entry
=> PP-3308 service look up on friendly url part 2

src/main/resources/migrations/00022_add_column_service_name_path_to_products.sql, src/main/resources/migrations/00023_add_column_product_name_path_to_products.sql, src/main/resources/migrations/00024_add_unique_two_column_constraint_to_products_for_product_path.sql
- Add column service_name_path
- Add column product_name_path
- Add unique reference on (service_name_path, product_name_path)
=> PP-3308 Add columns and add unique reference on products

src/main/resources/migrations/00025_drop_column_friendly_url_from_products.sql
- drop friendly_url column from products
=> PP-3308 Drop friendly_url column from products

src/main/java/uk/gov/pay/products/model/Product.java, src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoTest.java, src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- add columns service_name_path and product_name_path to ProductEntity
- add fields serviceNamePath and productNamePath to Product model
- add findByProductPath method to ProductDao
- add/refactor relevant tests
=> PP-3308 Add product path to ProductEntity and Product model

src/main/java/uk/gov/pay/products/service/ProductFinder.java, src/test/java/uk/gov/pay/products/service/ProductFinderTest.java
- add findByProductPath to ProductFinder
=> PP-3308 Add findByProductPath to ProductFinder

src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
- add endpoint (no link decorator yet)
=> PP-3308 Add findByProductPath endpoint

src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java, src/main/java/uk/gov/pay/products/config/ProductsModule.java, src/main/java/uk/gov/pay/products/model/Link.java, src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/java/uk/gov/pay/products/service/LinksDecorator.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java, src/test/java/uk/gov/pay/products/service/PaymentFinderTest.java, src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java, src/test/java/uk/gov/pay/products/service/ProductFinderTest.java, src/test/resources/config/test-it-config.yaml
- add friendly_url generation to LinksDecorator
- change pay_url to GET
- remove unused constants
- add/refactor relevant tests
=> PP-3308 add friendly url to link decorator

src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
- add serviceNamePath and productNamePath to product creation time
- add/update relevant tests
=> PP-3328 Add product path to product creation

src/main/java/uk/gov/pay/products/service/LinksDecorator.java, src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- add request validation of service_name_path and product_name_path for Adhoc type creation
- add/update relevant tests
=> PP-3328 Add Product Path validation for Adhoc type creation

src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/java/uk/gov/pay/products/service/ProductFinder.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/service/ProductFinderTest.java
- add new endpoint to ProductResource
- add new method to ProductFinder (deleteByExternalId)
=> PP-3556 Add DELETE endpoint to ProductResource

src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/java/uk/gov/pay/products/service/ProductFinder.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/service/ProductFinderTest.java
- add new endpoint to ProductResource
- add new method to ProductFinder (deleteByGatewayAccountIdandExternalId)
=> PP-3556 Add DELETE end point to ProductResource part 2

src/main/java/uk/gov/pay/products/persistence/dao/PaymentDao.java, src/main/java/uk/gov/pay/products/resources/PaymentResource.java, src/main/java/uk/gov/pay/products/service/PaymentFinder.java, src/test/java/uk/gov/pay/products/persistence/dao/PaymentDaoTest.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java
- add endpoint
- ad drelevant tests
=> PP-3726 add get payment by gateway account id and reference endpoint

src/main/resources/migrations/00026_add_column_reference_enabled_to_products.sql, src/main/resources/migrations/00027_add_column_reference_hint_to_products.sql, src/main/resources/migrations/00028_add_column_reference_label_to_products.sql, src/main/resources/migrations/00029_alter_column_reference_number_length_payments.sql
=> PP-3726 add reference related columns to products table

src/main/java/uk/gov/pay/products/model/Product.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java, src/test/java/uk/gov/pay/products/matchers/ProductMatcher.java, src/test/java/uk/gov/pay/products/persistence/dao/PaymentDaoTest.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- add reference fields
- validate reference if true
- add/update relevant tests
=> PP-3726 add reference feature to products creation

src/main/java/uk/gov/pay/products/service/LinksDecorator.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/service/ProductFinderTest.java
- add path to base payment uri
=> PP-3726 Add reference to payment link generation

src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/exception/BadPaymentRequestException.java, src/main/java/uk/gov/pay/products/exception/mapper/BadPaymentRequestExceptionMapper.java, src/main/java/uk/gov/pay/products/resources/PaymentResource.java, src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/main/java/uk/gov/pay/products/validations/PaymentRequestValidator.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- add user defined reference to PaymentResource
- add reference validation to PaymentCreator
- refactor PaymentCreator
- add BadPaymentRequestException with mapper
- add/refactor relevant tests
=> PP-3726 Add user defined reference handling to payments

src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/exception/ConflictingPaymentRequestException.java, src/main/java/uk/gov/pay/products/exception/mapper/ConflictingPaymentRequestExceptionMapper.java, src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- add relevant checks
- add new exception (409)
- add/update relevant tests
=> PP-3726 handle user defined reference duplication

docs/api_specification.md
-update api_specification.md with reference fields
=> PP-3726 Update API specs

src/main/resources/migrations/00030_drop_unique_constraint_gateway_id_reference_from_payments.sql, src/test/java/uk/gov/pay/products/persistence/dao/PaymentDaoTest.java
- remove unique constraint `payments_gateway_account_id_reference_number_key`
=> PP-3886 Remove unique constraint of payment reference

src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- remove the constraint of unique user entered reference number
=> PP-3886 Remove unique constrain for user entered reference

pom.xml
This upgrades Jetty from 9.4.10 to 9.4.11
=> PP-3938: Upgrade Dropwizard from 1.2.7 to 1.2.8

src/main/java/uk/gov/pay/products/client/publicapi/model/CardDetails.java, src/test/java/uk/gov/pay/products/matchers/PaymentResponseMatcher.java, src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
- We are adding first 6 digits of a card in publicapi, products needs to be aware of this
=> PP-4144 Add 6 first digits to card details

src/main/java/uk/gov/pay/products/service/PaymentCreator.java
Making this method recursive makes it more complex. Make it simpler (warning:
contains opinion)
=> BAU: Remove recursion from PaymentCreator.mergePaymentEntityWithReferenceNumberCheck

src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java, src/main/java/uk/gov/pay/products/model/PatchRequest.java, src/main/java/uk/gov/pay/products/model/Product.java, src/main/java/uk/gov/pay/products/service/ProductFinder.java, src/main/java/uk/gov/pay/products/validations/GatewayAccountRequestValidator.java, src/main/java/uk/gov/pay/products/validations/PaymentRequestValidator.java, src/test/java/uk/gov/pay/products/matchers/PaymentResponseMatcher.java, src/test/java/uk/gov/pay/products/service/GatewayAccountUpdaterTest.java
Address a bunch of random things found by IDEA's linter
=> BAU: Further IntelliJ-inspired cleanups

Jenkinsfile, src/main/java/uk/gov/pay/products/model/Link.java, src/main/java/uk/gov/pay/products/util/Errors.java, src/main/java/uk/gov/pay/products/util/RandomIdGenerator.java, src/main/java/uk/gov/pay/products/util/TrustStoreLoader.java, src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
* We can make use of `Objects`'s `equals` and `hashCode` methods to make our life easier
* One of our tests was using random numbers as input. This is not reliable.
* Remove some unused bits and bobs
=> BAU: Yet more IntelliJ-inspired cleanups

src/main/java/uk/gov/pay/products/persistence/dao/JpaDao.java, src/main/java/uk/gov/pay/products/persistence/dao/PaymentDao.java, src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java, src/test/java/uk/gov/pay/products/client/RestClientFactoryTest.java, src/test/java/uk/gov/pay/products/persistence/dao/PaymentDaoTest.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java, src/test/java/uk/gov/pay/products/service/PaymentFinderTest.java, src/test/java/uk/gov/pay/products/service/ProductFinderTest.java
IntelliJ found a few things it was irked by
* JpaDao had an unused method, the removal of which allowed some other code to go
* Some tests were a bit eager when it came to declaring shared variables
=> Misc: IntelliJ IDEA-inspired code cleanups

src/main/java/uk/gov/pay/products/resources/HealthCheckResource.java
Bring healthcheck code more in line with our other Java microservices.
Remove the logging of each healthcheck response - we can infer the result via
the HTTP access logs.
=> Simplify HealthCheckResource

pom.xml, src/test/java/uk/gov/pay/products/filters/RestClientLoggingFilterTest.java, src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java
Upgrade powermock from 1.7.4 to 2.0.0
Upgrade mockito from 2.8.47 to 2.24.0
Replace references to deprecated code in our tests
=> Mocking update

src/main/resources/migrations/00031_drop_column_service_name_from_products.sql
=> PP-4926 drop unused column service_name from products

src/main/resources/migrations/00032_add_column_language_to_products.sql
"language" is in quotes as it is a reserved word in SQL
=> PP-4987 Add language column to products table

.gitignore, Jenkinsfile, pom.xml, src/test/java/uk/gov/pay/products/infra/DropwizardAppWithPostgresRule.java, src/test/java/uk/gov/pay/products/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/products/pact/ProviderContractTest.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- Add contract test suite with provider states
- Enable contract tests as part of Jenkins build
=> PP-5005 Add provider contract tests for product UI

Dockerfile, Jenkinsfile, pom.xml
- Move all to Java 11 (pom.xml, docker base image, ci JAVA_HOME)
- CI should pass
=> PP-5051 Migrate to java 11

src/test/java/uk/gov/pay/products/pact/ProviderContractTest.java
_A brief description of the pull request:_
=> bau: Reduce pact provider test runs

pom.xml, src/test/java/uk/gov/pay/products/pact/ContractTestSuite.java
_A brief description of the pull request:_
=> PP-5670: Update pay java commons lib

pom.xml, src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/resources/config/config.yaml
_A brief description of the pull request:_
=> PP-5776: Configure server request logs to log in json format

src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/filters/LoggingMDCRequestFilter.java, src/main/java/uk/gov/pay/products/filters/LoggingMDCResponseFilter.java
Description:
- Adds gatewayAccountId, paymentExternalId, productExternalId and referenceNumber to MDC as they are all path params
=> PP-5893-Add-MDC-Logging-Filter

pom.xml, src/test/java/uk/gov/pay/products/infra/DropwizardAppWithPostgresRule.java, src/test/java/uk/gov/pay/products/persistence/dao/DaoTestBase.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- Upgrades dropwizard to v2.0.0
- Upgrades dropwizard-sentry
- Few fixes for test helper
=> PP-6001 Upgrade dropwizard from 1.3.17 to 2.0.0

src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/exception/ProductNotFoundException.java, src/main/java/uk/gov/pay/products/exception/mapper/ProductNotFoundExceptionMapper.java, src/main/java/uk/gov/pay/products/model/ProductMetadata.java, src/main/java/uk/gov/pay/products/persistence/dao/ProductMetadataDao.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductMetadataEntity.java, src/main/java/uk/gov/pay/products/service/ProductMetadataCreator.java, src/main/java/uk/gov/pay/products/service/ProductsMetadataFactory.java, src/main/java/uk/gov/pay/products/service/ProductsMetadataFinder.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductMetadataDaoIT.java, src/test/java/uk/gov/pay/products/service/ProductMetadataCreatorTest.java, src/test/java/uk/gov/pay/products/service/ProductsMetadataFinderTest.java
- add factory
- add ProductMetadataCreator
- add ProductsMetadataFinder
=> PP-6149 add product metadata factory

src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/config/ProductsModule.java, src/main/java/uk/gov/pay/products/model/ProductMetadata.java, src/main/java/uk/gov/pay/products/persistence/dao/ProductMetadataDao.java, src/main/java/uk/gov/pay/products/resources/ProductMetadataResource.java, src/main/java/uk/gov/pay/products/service/ProductMetadataCreator.java, src/main/java/uk/gov/pay/products/service/ProductsMetadataFinder.java, src/main/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidator.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductMetadataDaoIT.java, src/test/java/uk/gov/pay/products/resources/ProductMetadataResourceITest.java, src/test/java/uk/gov/pay/products/service/ProductsMetadataFinderTest.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- add endpoint for adding metadata
- add new methods to dao/finder to get existing metadata by product external id
- address comments in [PP-414](https://github.com/alphagov/pay-products/pull/414)
=> PP-6149 add products metadata resource endpoint

src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/exception/MetadataNotFoundException.java, src/main/java/uk/gov/pay/products/exception/ProductNotFoundException.java, src/main/java/uk/gov/pay/products/exception/mapper/MetadataNotFoundExceptionMapper.java, src/main/java/uk/gov/pay/products/persistence/dao/ProductMetadataDao.java, src/main/java/uk/gov/pay/products/resources/ProductMetadataResource.java, src/main/java/uk/gov/pay/products/service/ProductsMetadataCreator.java, src/main/java/uk/gov/pay/products/service/ProductsMetadataFactory.java, src/main/java/uk/gov/pay/products/service/ProductsMetadataUpdater.java, src/main/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidator.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductMetadataDaoIT.java, src/test/java/uk/gov/pay/products/resources/ProductMetadataResourceITest.java, src/test/java/uk/gov/pay/products/service/ProductsMetadataCreatorTest.java, src/test/java/uk/gov/pay/products/service/ProductsMetadataUpdaterTest.java, src/test/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidatorTest.java
- add new patch endpoint
- refactor validator
- add new dao method
- add new factory worker
=> PP-6167 add products metadata updater endpoint

src/main/java/uk/gov/pay/products/client/publicapi/PaymentRequest.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/test/java/uk/gov/pay/products/client/publicapi/PublicApiRestClientTest.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoIT.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java, src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
- send metadata if exists to publicapi when creating a payment
- update/add tests
=> PP-6161 send metadata to publicapi

src/main/java/uk/gov/pay/products/model/Payment.java, src/main/java/uk/gov/pay/products/model/ProductUsageStat.java, src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java, src/main/java/uk/gov/pay/products/persistence/entity/PaymentEntity.java, src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/java/uk/gov/pay/products/service/ProductFinder.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoIT.java, src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
* product usage model to contain payment count, last paid date and
referenced product
* expose list of usage models to resource endpoint
Performance depends on https://github.com/alphagov/pay-products/pull/449
=> PP-6325 Simple product usage route

.secrets.baseline, src/main/java/uk/gov/pay/products/persistence/dao/ProductMetadataDao.java, src/main/java/uk/gov/pay/products/service/ProductsMetadataFinder.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductMetadataDaoIT.java, src/test/java/uk/gov/pay/products/service/ProductsMetadataFinderTest.java
- Remove unused code and tests that were breaking CI
- Add .secrets.baseline
=> PP-7020 Fix Products Integration Tests

manifest.yml, src/main/resources/env-map.yml
- Configure secret paths and initialise gds pre-commit
=> PP-6913 Change secret paths and configure hooks

manifest.yml
Unbind paas db now peered dbs are used
=> PP-7020: Unbind paas db now peered dbs are used

src/main/java/uk/gov/pay/products/model/Product.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductMetadataEntity.java, src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java
- refactor create product to persist metadata when creating a new product.
- add tests
=> PP-7358 add persisting metadata when creating new product

src/main/java/uk/gov/pay/products/model/Product.java, src/main/java/uk/gov/pay/products/persistence/dao/ProductMetadataDao.java, src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/java/uk/gov/pay/products/service/ProductCreator.java, src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/main/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidator.java, src/test/java/uk/gov/pay/products/persistence/dao/ProductMetadataDaoIT.java, src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java, src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java, src/test/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidatorTest.java
- Adds functionality to validate and update metadata when PATCHing (editing) product.
with @sandorarpa
=> PP-7507 Process metadata when patching product

src/main/java/uk/gov/pay/products/client/publicapi/PaymentRequest.java, src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/main/java/uk/gov/pay/products/util/ProductType.java, src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/test/java/uk/gov/pay/products/client/publicapi/PublicApiRestClientTest.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java, src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java, src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
Add support for the `AGENT_INITIATED_MOTO` product type. This is similar to `ADHOC` in that it does not require a price but it doescnot require a service name path nor a product name path.
=> PP-7697 Add support for AGENT_INITIATED_MOTO product

src/test/java/uk/gov/pay/products/pact/ContractTest.java
Add new “three products with gateway account id 42 and type ADHOC exist” and “product with gateway account id 42 and type ADHOC and metadata exist” Pact states.
=> PP-7709 Add Pact states for products for gateway account with type

src/main/resources/migrations/00037_create_table_to_test_concourse_db_migration.sql
- Add a DB migration for products deployments to test the migration script
=> PP-7921 Add Real Products Migration

src/main/resources/migrations/00038_drop_test_concourse_db_migration.sql
- Rollback a DB migration for products deployments to test the migration script
=> PP-7921 Rollback Products Migration

README.md
Also to create a new build to test the deployment on fargate
=> PP-7991: Update readme

Jenkinsfile
Jenkins CI no longer needs to deploy.
=> PP-8695 Remove deploy step from Jenkins file

src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/main/java/uk/gov/pay/products/validations/PanDetector.java
Implemented enhanced logging to support additional filtering for this alert (option 3 as described in https://payments-platform.atlassian.net/browse/PP-8780)
Tests should pass
Code changes should make sense
=> PP-8780: log gateway account ID and reference length for suspected PAN in reference

.github/workflows/post-merge.yml
Follows the pattern of https://github.com/alphagov/pay-adminusers/pull/1287.
=> PP-9236: Run provider contract tests

.github/workflows/_run-pact-provider-tests.yml
See equivalent connector PR: https://github.com/alphagov/pay-connector/pull/3533
=> BAU: Fix provider contract tests to use the consumer and tag correctly

src/main/java/uk/gov/pay/products/model/Product.java, src/main/java/uk/gov/pay/products/model/ProductUpdateRequest.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/main/java/uk/gov/pay/products/service/ProductCreator.java, src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java, src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java
Return the amount_hint in all API responses that return a product.
Accept an amount_hint when creating a product and when updating a
product.
=> PP-9640 Return amount_hint field and allow update

openapi/products_spec.yaml, src/main/java/uk/gov/pay/products/model/Payment.java, src/main/java/uk/gov/pay/products/resources/HealthCheckResource.java, src/main/java/uk/gov/pay/products/resources/PaymentResource.java, src/main/resources/openapi-config.yaml
- Added OpenAPI specs for payments and healthcheck endpoints.
- Preview
=> PP-9456 OpenAPI specs for payments and healthcheck endpoints

src/main/java/uk/gov/pay/products/model/Product.java, src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java, src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/java/uk/gov/pay/products/service/ProductCreator.java, src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java, src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java, src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java
- new journey has been enabled for all products, we don't need a separate flag to enable it.
=> PP-9952 remove new payment link journey related code

openapi/products_spec.yaml, src/main/java/uk/gov/pay/products/resources/ProductResource.java, src/main/resources/migrations/00042_drop_column_new_payment_journey_enabled_from_products.sql
- this flag has been enabled for all products, we no longer need a separate flag column
=> PP-9952 drop column new_payment_link_journey_enabled from products

.gitignore, src/main/resources/migrations/00043_update_hint_columns_to_text_type.sql
Update columns amount_hint and reference_hint from type VARCHAR(255) to
text so that we can increase the number of characters allowed for these
fields.
Update .gitignore to ignore generated file dependency-reduced-pom.xml
=> PP-10019 Update hint columns to text type

.github/workflows/_run-pact-provider-tests.yml, .github/workflows/run-tests.yml
checked for Ubuntu 18.04 images and updated to ubuntu-latest
=> PP-10035 Updated ubuntu 18.04 to ubuntu-latest

.github/workflows/run-tests.yml, .pre-commit-config.yaml, .secrets.baseline, README.md, openapi/products_spec.yaml
Add a check in the GitHub actions workflow that runs on PR builds to check whether there are uncommitted changes after running `mvn compile`. If there are, this suggests that there have been changes to the API specification and the OpenApi file has not been regenerated. Fail the build when uncommitted changes are detected.
=> PP-10255 Check if there are uncommitted changes to OpenApi file

pom.xml
- prefer `dropwizard-dependencies` defined versions for `junit` and `mockito`
- send test output to file over console
=> BAU bump `dropwizard` -> 2.1.6

src/main/java/uk/gov/pay/products/exception/PaymentCreationException.java, src/main/java/uk/gov/pay/products/exception/mapper/PaymentCreationExceptionMapper.java, src/main/java/uk/gov/pay/products/persistence/entity/PaymentEntity.java, src/main/java/uk/gov/pay/products/service/PaymentCreator.java, src/main/java/uk/gov/pay/products/service/PaymentUpdater.java, src/main/java/uk/gov/pay/products/util/PublicAPIErrorCodes.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java, src/test/java/uk/gov/pay/products/service/PaymentUpdaterTest.java
- Handles P0105 error code from publicAPI and includes error identifier in the response to products-ui
- Redacts reference from products DB when the error code is P0105
=> PP-11167 Handle card number in payment link reference error code

pom.xml, src/main/java/uk/gov/pay/products/ProductsApplication.java, src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
Set up a prometheus metric endpoint /metrics.
Append ECS metadata info (via the PrometheusDefaultLabelSampleBuilder class in pay-java-commons) as default labels.
=> PP-11223: Set up prometheus metrics

src/main/java/uk/gov/pay/products/persistence/dao/PaymentDao.java, src/test/java/uk/gov/pay/products/persistence/dao/PaymentDaoIT.java, src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
Get payments to delete by max date and a max number of payments.
=> PP-11231: Get payments for deletion

.secrets.baseline, README.md, openapi/products_spec.yaml, src/main/java/uk/gov/pay/products/config/ExpungeHistoricalDataConfig.java, src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java, src/main/java/uk/gov/pay/products/config/ProductsModule.java, src/main/java/uk/gov/pay/products/resources/PaymentResource.java, src/main/java/uk/gov/pay/products/service/PaymentDeleter.java, src/main/java/uk/gov/pay/products/service/PaymentFactory.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/products/resources/IntegrationTest.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceIT.java, src/test/java/uk/gov/pay/products/service/PaymentDeleterTest.java, src/test/java/uk/gov/pay/products/utils/TestHelpers.java, src/test/resources/config/test-it-config.yaml
Implement `/v1/tasks/delete-historical-data`.
=> PP-11231: Implement delete payments endpoint

.github/workflows/_run-pact-provider-tests.yml, .github/workflows/run-tests.yml, src/test/java/uk/gov/pay/products/infra/DropwizardAppWithPostgresRule.java, src/test/java/uk/gov/pay/products/persistence/dao/DaoTestBase.java
Bump Postgres containers to 15.2, like we have in our real envs.
=> PP-11895-upgrade-postgres-container

pom.xml
- remove redundant versionioning of wiremock
- correct spelling of swagger
=> PP-12176 remove redundant version

.secrets.baseline, openapi/products_spec.yaml, src/main/java/uk/gov/pay/products/resources/PaymentResource.java, src/test/java/uk/gov/pay/products/resources/PaymentResourceIT.java
The only place that calls this API has been [deleted](https://github.com/alphagov/pay-products-ui/pull/2663/files\#diff-dfbb117197892396568fc2fb68b9ef4ccb7d6923a49ca76f4acf0dd61ad7aac0L126).
=> bau: Delete /v1/api/payments/{gatewayAccountId}/{referenceNumber}

.github/dependabot.yml, .github/workflows/_run-tests.yml, .github/workflows/codeql.yml, Dockerfile, m1/arm64.Dockerfile, pom.xml, src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java
- Upgrades to Java 21
- Removed duplicate declaration of `dropwizard-migrations` and `mockito-junit-jupiter` libraries
=> PP-12725 Upgrade to Java 21

src/main/java/uk/gov/pay/products/config/ProductsModule.java, src/main/java/uk/gov/pay/products/service/PaymentDeleter.java, src/test/java/uk/gov/pay/products/service/PaymentDeleterTest.java
=> PP-12791 Replace Clock with InstantSource

README.md, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
Bind to 127.0.0.1 by default instead of 0.0.0.0
I followed the exact same testing strategy as https://github.com/alphagov/pay-connector/pull/5539 and achieved the same results
=> PP-13145: Accept BIND_HOST env var and default to localhost
