- Jenkinsfile
At this stage, this is a bare-bones repo. In order to integrate with
the end to end tests, we need to build, unit test and push a container
to Docker Hub.
This Jenkinsfile should hopefully be just enough to get that done.
As the code evolves and we have something to integrate with the
end-to-end tests, then this Jenkinsfile can have the additional steps
added.
> Add simple Jenkinsfile, no end-to-end tests.

- Jenkinsfile
It seems credstash requires an AWS_REGION to work with. Although in PaaS we haven't got such a context, adding this solely for the purpose of accessing credstash
Also adding the missing postgres container pull
> PP-2668 Adding DEFAULT_AWS_REGION env variable

- src/main/java/uk/gov/pay/products/client/publicapi/PaymentResponse.java
- src/main/java/uk/gov/pay/products/client/publicapi/PublicApiResponseErrorException.java
- src/main/java/uk/gov/pay/products/client/publicapi/model/CardBrand.java
- src/main/java/uk/gov/pay/products/client/publicapi/model/CardDetails.java
- src/main/java/uk/gov/pay/products/client/publicapi/model/Links.java
- src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java
- src/main/java/uk/gov/pay/products/config/ProductsModule.java
- src/main/java/uk/gov/pay/products/persistence/entity/PaymentEntity.java
- src/main/java/uk/gov/pay/products/resources/PaymentResource.java
- src/main/java/uk/gov/pay/products/resources/ProductResource.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/main/java/uk/gov/pay/products/service/PaymentCreatorDownstreamException.java
- src/main/java/uk/gov/pay/products/service/PaymentCreatorNotFoundException.java
- src/main/java/uk/gov/pay/products/service/PaymentFactory.java
- src/main/java/uk/gov/pay/products/service/ProductCreator.java
- src/main/java/uk/gov/pay/products/service/ProductFactory.java
- src/test/java/uk/gov/pay/products/matchers/PaymentEntityMatcher.java
- src/test/java/uk/gov/pay/products/matchers/PaymentRequestMatcher.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java
`PaymentCreator` service takes care of all concerns regarding the creation of a new payment for a given product. The sole entry point of the service `doCreate` expects the `id` of a product for which a new payment will be created and returned.
1. The initial pre-operation step looks up the product and adds to it an empty payment with the status of `CREATED`. If the product doesn't exist a `PaymentCreatorNotFoundException` is thrown.
2. The actual operation then submits a payment creation request to PublicAPI which maps the outcome to our `PaymentEntity`. The status is updated to either `SUCCESS` or `ERROR` depending on whether the request is successful or not.
3. Finally the post-operation saves the payment updates. If the payment operation fails an `PaymentCreatorDownstreamException` is …
> Pp 2672/create payment for a product part 3

- pom.xml
- Downgrade PSQL driver version to suppress a red herring SEVERE log msg by the PSQL guys. It is confusing and we should be able to decide what to do with the error.
with @kakumara
> PP-2672 Downgrade PSQL driver version

- src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java
- src/main/java/uk/gov/pay/products/config/ProductsModule.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
- src/test/resources/config/test-it-config.yaml
#WHAT 
This config name change is to make it more explicit that the URL expected here is not the Product UI base URL but the full URL to the paying resource.
> PP-2672 Renamed `productUiUrl` to `productUiPayUrl`

- src/main/java/uk/gov/pay/products/client/publicapi/PublicApiRestClient.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/test/java/uk/gov/pay/products/client/publicapi/PublicApiRestClientTest.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStubExpectation.java
Improved version of `PublicApiRestClient` taking into account the `Bearer` API token that needs to be passed in the header of all PublicAPI requests for obvious security reasons. The authorization token is in the form of `Bearer + API token` where the API token is specific for each product.
> PP-2672 Improved version of `PublicApiRestClient` taking into account the `Bearer` API token

- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
Fix to send the right information to PublicAPI when creating a payment. PublicAPI expects a `Description` field which should be what we hold as product name (instead of product description).
> PP-2672 Fix to send the right information to PublicAPI when creating a payment

- Jenkinsfile
Triggering `runParameterisedEndToEnd` with the test profile `end2end-products`. It also disables the accept tests and zap tests
> PP-2855 add end2end test step for builds

- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/main/java/uk/gov/pay/products/util/PaymentStatus.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- change the payment status enum from 'SUCCESS' to 'SUBMITTED'
Currently we mark a payment status `SUCCESS` when a charge was successfully created on publicapi. This leads to confusion as the actual payment might not be successful at all. To avoid the confusion we mark it as `SUBMITTED`.
At a later point we will reintroduce `SUCCESS` to cache the status of a payment.
> PP-2672 Change payment status enum from SUCCESS to SUBMITTED

- src/main/java/uk/gov/pay/products/model/Payment.java
- src/main/java/uk/gov/pay/products/service/PaymentFinder.java
- src/test/java/uk/gov/pay/products/service/PaymentFinderTest.java
- add new non-transactional find method to PaymentFinder
- refactor PaymentFinder accordingly
- add payment's govuk status checking from publicapi
- add tests
We only check payment status if Product Payment status is `SUBMITTED`.
> PP-2762 Implement new service method to return govuk's payment status

- src/main/java/uk/gov/pay/products/config/ProductsModule.java
`PaymentCreator` service had a dependency with `ProductsConfiguration` which could never be resolved because `Guice` injector didn't have the dependency explicitly bound to it.
> PP-2672 Bugfix: Setup Guice injector to bind `ProductsConfiguration` as a depency

- pom.xml
- src/test/java/uk/gov/pay/products/infra/PostgresContainer.java
- Current integration tests are using a non ideal manually built Postgres image for testing. Even less ideal is pulling the image locally when it does not exist (example as in new machines, docker images clean up, changed a reference to a new image)
- Pull explicitly the docker image before running the tests
- Upgrade docker-client (test scope) version from 8.1.0 -> 8.9.2
> PP-2959 Explicit docker pull postgres image for testing

- Jenkinsfile
Moving away from having required to declare specific maven profiles for various category of end2end builds. `end2end-tagged` profile is generic enough to run any kind of test groups with necessary includes and excludes. This moves the products to use the `end2end-tagged` profile.
> PP-2923 migrating to end2end-tagged maven test profile

- pom.xml
This is required for DBHostnameVerifier check on postgres connection.
> PP-2916 adding mandatory dependency as a top level dependency.

- Jenkinsfile
- src/main/java/uk/gov/pay/products/ProductsApplication.java
- src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java
- src/main/java/uk/gov/pay/products/config/ProxyConfiguration.java
- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
We now need this as we are in AWS as all outbound comms needs to be via the proxy.
Adding an extra config param `enabled` just to make sure we have a mechanism of disabling it in PaaS (until we stick with PaaS, then we can remove this condition)
> PP-2925 add proxy configuration for products

- Jenkinsfile
This needs to be done until we fully migrate over to AWS.
> PP-2996 Trigger products to deploy both on PaaS as well as AWS

- Jenkinsfile
Until the selfservice CNAME issue (PROMOTED_ENV and PUBLIC_ENV var) fixed on CI and DEPLOY.
> PP-2996 disable smoke test on AWS

- src/main/java/uk/gov/pay/products/model/Payment.java
- src/main/java/uk/gov/pay/products/persistence/entity/PaymentEntity.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/main/resources/migrations/00013_add_unique_two_column_constraint_to_payments.sql
- src/test/java/uk/gov/pay/products/fixtures/PaymentEntityFixture.java
- src/test/java/uk/gov/pay/products/persistence/dao/PaymentDaoTest.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- add/refactor payments entity to cater for DB changes (new columns)
- add unique two columns constraint to  gateway_account_id and reference_number on payments    - add logic to set random reference number at payment creation
- add error handling in case gateway_account_id and reference_number uniqueness is violated
- update/add tests
> PP-3031 Add Random Reference Number changes to entity

- Jenkinsfile
As it is already tagged after PaaS deployment.
> PP-2996 avoid tagging after AWS deployment

- Jenkinsfile
1. Enabling smoke test in products (AWS)
2. set PROMOTED_ENV to true. So that smoke tests will use non instance specific environment URLs. see (alphagov/pay-jenkins-library#23)
> PP-2996 Enable smoke test and Specify PROMOTED_ENV

- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java
- src/main/java/uk/gov/pay/products/util/ProductType.java
- src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java
- src/main/java/uk/gov/pay/products/validations/RequestValidations.java
- src/main/resources/migrations/00011_add_column_type_to_products.sql
- src/main/resources/migrations/00014_add_column_type_to_products.sql
- src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
- src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java
- src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
This introduces a type for products. We currently only support 3 different types:
* `DEMO`
* `PROTOTYPE` 
* `ADHOC`
Existing products that were created before this will all be migrated to be of type `PROTOTYPE`.
- Added the product `type` field of type `VARCHAR(255)` which backfills with default value of `PROTOTYPE`.
- Created the product `type` enum.
- Added the product `type` attribute to the product model, making it in request/response payloads of product APIs.
- Added the product `type` attribute to the product entity, making it persistent.
- Added request validation, making product type mandatory and been one of the valid types `DEMO`, `PROTOTYPE`, `ADHOC`.
- Set the type to be `PROTOTYPE` as default in the database scheme migration.
> PP-3032/create adhoc products

- src/main/java/uk/gov/pay/products/ProductsApplication.java
- src/main/java/uk/gov/pay/products/config/ProductsModule.java
- src/main/java/uk/gov/pay/products/model/GatewayAccountRequest.java
- src/main/java/uk/gov/pay/products/model/PatchRequest.java
- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/resources/GatewayAccountResource.java
- src/main/java/uk/gov/pay/products/service/GatewayAccountFactory.java
- src/main/java/uk/gov/pay/products/service/GatewayAccountUpdater.java
- src/main/java/uk/gov/pay/products/validations/GatewayAccountRequestValidator.java
- src/test/java/uk/gov/pay/products/resources/GatewayAccountResourceTest.java
- src/test/java/uk/gov/pay/products/service/GatewayAccountUpdaterTest.java
- src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- src/test/java/uk/gov/pay/products/validations/GatewayAccountRequestValidatorTest.java
Implement GatewayAccountResource to update Service Name in `products`
- add validator [ece1427](https://github.com/alphagov/pay-products/commit/ece1427847646fecc58a208bae5d80287fac53de)
- add GatewayAccountUpdater and GatewayAccountRequest, refactor Product to create Product from ProductEntity [5b4f6dc](https://github.com/alphagov/pay-products/commit/5b4f6dc48a8ae8305bfcbd0dd9ba7defc78bc95a)
- add GatewayAccountFactory and configure ProductsApplication to inject GatewayAccountFactory [e5b061b](https://github.com/alphagov/pay-products/commit/e5b061b89c15aed10179c48477b59f19a54dc77d)
- add GatewayAccountResource and configuration to Application and Module [ecd5ea3](https://github.com/alphagov/pay-products/commit/ecd5ea34f36a57964d594db18b5540b639792ab9)
- add/refactor relevant tests
- …
> PP-3048 Keep service name in sync

- src/main/java/uk/gov/pay/products/service/GatewayAccountUpdater.java
- src/main/java/uk/gov/pay/products/validations/GatewayAccountRequestValidator.java
- src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java
- src/main/java/uk/gov/pay/products/validations/RequestValidations.java
- src/test/java/uk/gov/pay/products/resources/GatewayAccountResourceTest.java
- src/test/java/uk/gov/pay/products/service/GatewayAccountUpdaterTest.java
- src/test/java/uk/gov/pay/products/validations/GatewayAccountRequestValidatorTest.java
- Add path and operation validations to GatewayRequestValidator [f4ac5a4](https://github.com/alphagov/pay-products/commit/f4ac5a480804a0e69cf8214ef7e83f2ffb6bc5bd)
- Refactor GatewayAccountUpdater to use a generic BiConsumer to update DB [a10df78](https://github.com/alphagov/pay-products/commit/a10df787a9120ae6bbaac26b3bdd9e49f438795f)
- Add/refactor/fix tests
> PP-3048 Keep service name in sync part 2

- docs/api_specification.md
- src/main/java/uk/gov/pay/products/resources/PaymentResource.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/main/java/uk/gov/pay/products/validations/PaymentRequestValidator.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- src/test/java/uk/gov/pay/products/validations/PaymentRequestValidatorTest.java
As part of adhoc payment journey, the paying user is able to provide the payment amount. This requires using that captured amount used during payment/charge creation which actually overrides the products price. 
There is not special CAP at the moment and the user is able to provide the maximum amount that payment platform can take at the moment.
> PP-3034 payment price override

- src/main/java/uk/gov/pay/products/resources/GatewayAccountResource.java
- src/test/java/uk/gov/pay/products/resources/GatewayAccountResourceTest.java
- change return code. Products does not own GAs and thus it does not need to tell the caller that a specific gateway is not exists on it.
> PP-3048 Change 404 to 202 of GatewayAccount endpoint return code

- docker-startup.sh
This not existing was causing problems in endtoend, where the app was coming up before the database and then
failing to start.
> PP-3186: Reenable wait on dependencies

- Jenkinsfile
We are no longer in PaaS so removing this step.
Also made deploy job to tag after deployment.
> PP-3204 remove paas deployment

- src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java
- src/main/resources/migrations/00018_alter_column_service_name_length_products.sql
- src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- Service names validated to be 50 characters length across all the microservices, at least until Service Names comes from a single source we need to make this work for consistency.
> PP-3295 Service Name validation consistent across microservices

- docs/api_specification.md
- src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java
- src/main/resources/migrations/00019_alter_column_price_null_products.sql
- src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
For adhoc products with non fixed amount(where user enters an amount) it does not make sense to capture the price field. We can use this price field being available to support the adhoc fixed price journey
> PP-3259 make price optional adhoc Products

- Dockerfile
- docker-startup.sh
- run-with-chamber.sh
When running in ECS we need to use chamber to fetch the secrets
When running in ECS we need to not run the migrations on the app server
so we need to configure whether to run the migrations.
I'm going to change e2e to use the correct variables but until that is
updated RUN_MIGRATIONS should default to true
solo @tlwr
> PP3253: Add run-with-chamber.sh to Dockerfile

- docker-startup.sh
e2e has now passed, need to set this to false so that the ECS containers
start up without migrations
solo @belindac
> PP-3253 ECSify Products in Test

- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java
- src/main/java/uk/gov/pay/products/resources/GatewayAccountResource.java
- src/main/java/uk/gov/pay/products/resources/PaymentResource.java
- src/main/java/uk/gov/pay/products/resources/ProductResource.java
- src/main/java/uk/gov/pay/products/service/LinksDecorator.java
- src/main/java/uk/gov/pay/products/service/ProductFinder.java
- src/test/java/uk/gov/pay/products/matchers/ProductMatcher.java
- src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoTest.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
- src/test/java/uk/gov/pay/products/service/ProductFinderTest.java
- src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
While creating new ` Prototype Links ` and ` Payment Links `in selfservice we were vulnerable to insecure direct object references as we failed to verify that products belong to gateway accounts for certain operations. To mitigate this problem, product API has been updated to explicitly force to provide the gateway account id in the path for all operations. 
* Substituted all variables in resource paths by their value to make it more
readable what the actual path for a resource is. This is consistent with the 
approach taken in other `Dropwizard` project such as Connector. 
* Added a method called `findByGatewayAccountIdAndExternalId` in `ProductDao` that restraints the lookup of products by their respective accounts. As part of this, a few missing tests have also been retrofitted. 
* …
> PP-3441 Insecure direct object reference vulnerability

- README.md
- docs/api_specification.md
- src/main/java/uk/gov/pay/products/resources/ProductResource.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
The new endpoints constraining all product operations by gateway accounts introduced in c49ca1e0abaac1386e3f4b2471a277a4fcda1b53, also deprecated the original endpoints. As it became apparent that the original endpoints were also needed, this change reinstates them and adds missing tests.
To be merged only after:
- https://github.com/alphagov/pay-selfservice/pull/703
- https://github.com/alphagov/pay-products-ui/pull/67
> PP-3441 Reinstated endpoints previously deprecated

- pom.xml
This upgrades Jackson from 2.9.1 to 2.9.6 and Jetty from 9.4.7.v20170914 to
9.4.10.v20180503
> PP-3935: Upgrade Dropwizard from 1.2.2 to 1.2.7

- src/main/java/uk/gov/pay/products/client/publicapi/PaymentResponse.java
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
When deserialising a payment response from public API into a `PaymentResponse` object, ignore any unknown properties that are encountered in the JSON.
This makes it possible to add new properties to the payment responses returned by public API without having to modify this project.
> PP-4095 Ignore unknown properties when deserialising payment

- src/main/java/uk/gov/pay/products/client/publicapi/PaymentResponse.java
Email and user address should never be logged, removing them from the `toString()` method should suffice
> PP-3926 Remove email and card details from PaymentResponse

- src/main/java/uk/gov/pay/products/client/publicapi/model/Address.java
- src/main/java/uk/gov/pay/products/client/publicapi/model/CardDetails.java
- src/main/java/uk/gov/pay/products/client/publicapi/model/Links.java
- src/main/java/uk/gov/pay/products/client/publicapi/model/PaymentState.java
- src/main/java/uk/gov/pay/products/client/publicapi/model/RefundSummary.java
- src/main/java/uk/gov/pay/products/client/publicapi/model/SettlementSummary.java
Fix response objects to ignore unknown fields. This is needed as we're extending publicapi responses and they're breaking products.
add `@JsonIgnoreProperties(ignoreUnknown = true)` to relevant classes
> PP-4297 fix response objects to ignore unknown fields

- pom.xml
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStubExpectation.java
This is a merger of https://github.com/alphagov/pay-products/pull/141 and https://github.com/alphagov/pay-products/pull/140
> BAU: Upgrade mockserver to 5.5.0

- src/test/resources/config/test-it-config.yaml
Downgrade the logging level of liquibase during test runs. Liquibase logs all
its SQL which clutters the build log.
> Silence liquibase noise during tests

- src/main/java/uk/gov/pay/products/healthchecks/DatabaseHealthCheck.java
- src/test/java/uk/gov/pay/products/infra/DropwizardAppWithPostgresRule.java
- src/test/java/uk/gov/pay/products/persistence/dao/DaoTestBase.java
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
* Use try with resources to manage the lifecycle of JDBC `Connection` objects
* Use IntelliJ's preferred `L` designator for `long` literals
* Remove an unused constructor in `DropwizardAppWithPostgresRule`
* Tighten a couple of access levels
* Turn an unused field into a method variable
> BAU: More IntelliJ-inspired tidyups

- src/main/java/uk/gov/pay/products/resources/HealthCheckResource.java
We can be a lot more functional when generating our healthcheck responses, given we're basically just transforming a `Map` into another `Map` and making an assertion over its contents.
> BAU: Refactor healthcheck processing

- pom.xml
- src/main/java/uk/gov/pay/products/healthchecks/DependentResourceWaitCommand.java
- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
Change the log format to match other microservices. Remove ANSI colours and trailing whitespace.
Also use the new single-argument constructor for `ApplicationStartupDependentResourceChecker` in `DependentResourceWaitCommand`
> PP-4660, PP-4602: Use simpler database polling code, cleanup logging

- src/test/java/uk/gov/pay/products/filters/RestClientLoggingFilterTest.java
Mockito has deprecated org.mockito.runners.MockitoJUnitRunner in favour of
org.mockito.junit.MockitoJUnitRunner
This was already updated in all our tests apart from
RestClientLoggingFilterTest
> Avoid Mockito deprecation warning

- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
Prevent Powermock from attempting to load particular classes which would result in illegal access and failure to compile. This is necessary for Java 11 upgrade.
Add an annotation that tells Powermock to ignore attempting to load particular classes. Without this post java 8, in this particular instance it attempts to illegally access `javax.xml.parsers.FactoryFinder` when mocking our `PublicApiRestClient`.
> PP-4954 Make PowerMock ignore classes it cannot load.

- pom.xml
- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java
- src/main/java/uk/gov/pay/products/validations/RequestValidations.java
- src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- Add uk.gov.pay.model dependency to access SupportedLanguage
- Remove unused "service_name" validations
- Add validation for valid enum value and re-use for validating "type" is a valid ProductType
> PP-4987 Add validations for language field in ProductRequest

- docs/api_specification.md
- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java
- src/main/resources/META-INF/persistence.xml
- src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
- src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java
- src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
Add language field to ProductEntity and Product so that it is accepted by the create product endpoint, persisted to the database, and returned by the get product endpoints.
Default language to "en" when deserialising Product from JSON payload if the field is not present.
> PP-4987 Add language field to product

- src/main/java/uk/gov/pay/products/client/publicapi/PaymentRequest.java
- src/main/java/uk/gov/pay/products/client/publicapi/PaymentResponse.java
- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/test/java/uk/gov/pay/products/client/publicapi/PublicApiRestClientTest.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceTest.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
Provide the language of the product when calling Public API to create the payment and expect it in the Public API response.
> PP-5004 Send product language when creating a payment

- src/test/java/uk/gov/pay/products/pact/ProviderContractTest.java
Just specified a gateway account on an existing state and added another state label so that selfservice pact tests can be switched on.
> PP-5017 Add provider states for selfservice pact tests

- README.md
- src/main/resources/config/config.yaml
Update README.md to describe all environment variables used by the `products`
microservice as per `docker-startup.sh` and the Dropwizard configuration file.
Also set sensible defaults for `PORT` and `ADMIN_PORT` in the Dropwizard config
file, to match the settings in the `Dockerfile`.
> PP-5076: Document all environment variables used by products

- src/main/java/uk/gov/pay/products/service/ProductCreator.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceTest.java
- src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java
- Selfservice now sends the reference fields when making a request to update a product. Use this when updating the product
> PP-4493 Expect Reference information in update product request

- Jenkinsfile
- build-local.sh
- pom.xml
- src/test/java/uk/gov/pay/products/persistence/dao/PaymentDaoIT.java
- src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoIT.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceIT.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java
Integration tests are slow. They involve starting a PostgreSQL container and
instantiating Dropwizard.
Split them from the unit tests and run the unit tests with the surefire plugin
instead.
Rename integration tests to match the default include/exclude rules for the
surefire and failsafe maven plugins. By default, the failsafe plugin will
include any tests matching IT*.java, *IT.java and *ITCase.java. This was not
the naming scheme our integration tests had, so fix that.
Since unit tests are so quick, we no longer need to skip them when running
local builds.
maven's 'package' target doesn't include running integration tests, so switch
to using the 'verify' target during CI builds, which is what we should've been
doing anyway.
> Separate integration tests from unit tests

- README.md
- src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java
- src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java
- src/main/java/uk/gov/pay/products/validations/RequestValidations.java
- src/main/resources/config/config.yaml
- src/test/java/uk/gov/pay/products/validations/PaymentRequestValidatorTest.java
- src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- src/test/resources/config/test-it-config.yaml
Add a configuration parameter and environment variable (SECURE_RETURN_URLS) to
permit the 'return_url' of a product to be non-https
> Make secure return URLs optional

- src/main/java/uk/gov/pay/products/ProductsApplication.java
- src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java
- src/test/java/uk/gov/pay/products/validations/PaymentRequestValidatorTest.java
Remove an unused import from a test
Define the graphite port number as an integer and let the Dropwizard configuration parser handle the parsing of it.
> Define the graphite port number as an integer in configuration

- pom.xml
- src/test/java/uk/gov/pay/products/pact/ContractTest.java
- src/test/java/uk/gov/pay/products/pact/ContractTestSuite.java
- src/test/java/uk/gov/pay/products/pact/ProductsUIContractTest.java
- src/test/java/uk/gov/pay/products/pact/SelfServiceContractTest.java
Currently when a consumer build is kicked off, the provider contract test will
run in its entirety. For example, in a selfservice build, the products provider
contract tests will run as well. However, what is run is:
products-ui->products
selfservice->products
We really only want to run selfservice->products in this case.
This commit will allow a dynamic creation of the test suite to run based on a
CONSUMER system property. This will mean shorter run times when a provider
contract test is run as part of a specific consumer build.
_A brief description of the pull request:_
* Added new API …
> PP-5670: Specify the consumer when running contract test

- src/main/java/uk/gov/pay/products/filters/LoggingMDCResponseFilter.java
We shouldn't use MDC.clear as LoggingMDCResponseFilter happens before the
LoggingFilter
(https://github.com/alphagov/pay-java-commons/blob/master/logging/src/main/java/uk/gov/pay/logging/LoggingFilter.java)
is called. This would remove the x_request_id needed in the LoggingFilter.
> PP-5893: Manually clear keys

- Jenkinsfile
The Jenkins pipeline pre-pulls a Postgres 9.4.4 container used by the test suite. This isn't actually used by the test suite. 
The container used by the tests is specified in the pay-java-commons library. 
This configures DB tests start and run Postgres 9.6.6 or which ever version was specified in a given version of `pay-java-commons`
See: https://github.com/alphagov/pay-java-commons/blob/master/testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresContainer.java#L62
The 9.4.4 container is no longer on docker-hub causing the existing build pipeline to fail.
The test suite should now pull the correct Postgres version.
> Remove Postgres container pre-pull from build pipeline

- src/main/java/uk/gov/pay/products/client/publicapi/Internal.java
- src/main/java/uk/gov/pay/products/client/publicapi/PaymentRequest.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/test/java/uk/gov/pay/products/client/publicapi/PublicApiRestClientTest.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
- Public API accepts new object `internal` (https://github.com/alphagov/pay-publicapi/pull/829 ) on create payment endpoint payload. Added `source` flag with value `CARD_PAYMENT_LINK` to create payment payload
- Updated relevant tests
> PP-6020 Send source flag with create payment request

- .travis.yml
Adds a simple .travis.yml build configuration for running CI java build tasks.
> Add .travis.yml build configuration

- src/main/resources/migrations/00033_add_products_metadata_table.sql
- Adds a migration for the `products_metadata` table to products with
the correct `UNIQUE` and `FOREIGN KEY` constraints.
> PP-6149 Add Products Metadata Table

- src/main/resources/migrations/00034_add_column_version_to_products_metadata.sql
- I forgot to add the standard version column to `products_metadata`,
this adds it where it is missing.
> PP-6149 Add Products Metadata Version Column

- src/main/java/uk/gov/pay/products/persistence/dao/ProductMetadataDao.java
- src/main/java/uk/gov/pay/products/persistence/entity/ProductMetadataEntity.java
- src/test/java/uk/gov/pay/products/fixtures/ProductMetadataEntityFixture.java
- src/test/java/uk/gov/pay/products/persistence/dao/ProductMetadataDaoIT.java
- Adds `ProductMetadataEntity` and `ProductMetadataDao` to enable
programmatic access of the `products_metadata` table in the products
database.
> PP-6149 Add ProductMetadata Entity and Dao

- src/main/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidator.java
- src/test/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidatorTest.java
- keys have to be unique (case insensitive) compared to existing keys
- only one key-value pair is allowed
- keys are limited to 20 characters
- values are limited to 50 characters
- add tests
> PP-6149 add product metadata validation

- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/model/ProductMetadata.java
- src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java
- src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java
- src/main/java/uk/gov/pay/products/persistence/entity/ProductMetadataEntity.java
- src/main/java/uk/gov/pay/products/service/ProductMetadataCreator.java
- src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java
- src/test/java/uk/gov/pay/products/fixtures/ProductMetadataEntityFixture.java
- src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoIT.java
- src/test/java/uk/gov/pay/products/persistence/dao/ProductMetadataDaoIT.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java
- src/test/java/uk/gov/pay/products/service/ProductCreatorTest.java
- src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- When a payment link is returned as JSON, the metadata that relates to that payment link instance should be contained within the response object under the `metadata` tag.
> PP-6165 List Metadata For Payment Link

- src/test/java/uk/gov/pay/products/pact/ContractTest.java
- src/test/java/uk/gov/pay/products/pact/SelfServiceContractTest.java
- add a selfservice pact test that includes metadata for a paymentlink
> PP-6160 add a selfservice pact test for a paymentlink with metadata

- src/main/java/uk/gov/pay/products/util/Errors.java
- src/main/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidator.java
- src/test/java/uk/gov/pay/products/resources/ProductMetadataResourceITest.java
- Adds an `ErrorIdentifier` field to the Errors object, allowing for
extra descriptive information to be returned if needed.
- Adds a test to ensure this functionality is as expected.
> PP-6153 Add ErrorIdentifier field to Errors object

- src/main/java/uk/gov/pay/products/resources/ProductMetadataResource.java
- src/main/java/uk/gov/pay/products/service/ProductsMetadataDeleter.java
- src/main/java/uk/gov/pay/products/service/ProductsMetadataFactory.java
- src/test/java/uk/gov/pay/products/resources/ProductMetadataResourceITest.java
- Adds a DELETE endpoint for metadata which allows for metadata on a
product to be removed via an API.
- Adds tests to ensure happy and failure paths both work as expected.
> PP-6157 Add Delete Endpoint For Metadata

- src/main/resources/migrations/00035_index_columns_for_usage_report.sql
* index product type to allow the report to ignore demo and prototype
links
* index payment date_created to allow aggregate `MAX` in report
> PP-6325 Indexes for product usage reports

- src/test/java/uk/gov/pay/products/resources/ProductMetadataResourceIT.java
Surefire plugin which runs the `test` goal includes `**/*Test.java`
(amongst other patterns) so the `ProductMetadataResourceITest` was
running with `mvn test`. This renames it to `ProductMetadataResourceIT` so it
runs with the `verify` goal (Failsafe plugin). This follows our
separation of unit and integration tests.
> PP-6444 Rename Integration Test so it only runs under verify goal

- src/test/java/uk/gov/pay/products/pact/ProductsUIContractTest.java
- src/test/java/uk/gov/pay/products/pact/SelfServiceContractTest.java
We're using a different pact broker for ci on concourse so make the pact
broker host configurable. The default value is the existing broker used
by Jenkins CI.
> PP-6445 Make Pact Broker Host configurable

- src/main/resources/migrations/00036_alter_column_metadata_value_to_varchar_100.sql
Database migration to alter the type of the `metadata_value` column of the `products_metadata` table from `VARCHAR(50)` to `VARCHAR(100)`.
Tested this locally and it did the right thing.
The version of PostgreSQL we use is recent enough increasing the size of a `VARCHAR` column does not rewrite the entire table. It does require an access exclusive lock on the table but in production `products_metadata` only has 90 rows so this will be fine.
> PP-7067 Alter type of metadata_value column to be VARCHAR(100)

- .secrets.baseline
- src/main/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidator.java
- src/test/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidatorTest.java
Update `ProductsMetadataRequestValidator` (and its unit tests) to rely on constants in ExternalMetadata (which is imported from Pay Java commons) for things like the maximum number of characters allowed for metadata values associated with a product.
This has no functional effect other than increasing the character limit for a metadata value from 50 to 100. The necessary database migration to enable this was commit 32ae783331377b719910ab91df1b521a0f12d59f.
Public API and connector have already been updated to allow 100 characters rather than 50.
> PP-7067 Increase maximum metadata value length from 50 to 100

- src/main/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidator.java
- src/test/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidatorTest.java
Due a typo, the maximum key length was being restricted to 10 characters (the number of allowed key-value pairs) rather than 30.
> PP-7067 Fix maximum key length validation check

- src/main/java/uk/gov/pay/products/client/publicapi/PublicApiRestClient.java
- src/main/java/uk/gov/pay/products/resources/ProductResource.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
Stop logging the entire request body sent from the client to prevent
unwanted fields being logged (present and future).
Explicitly include the following fields on payment link creation:
* gateway account ID
* product name
* product type
Use structured logging to only log explicit fields from public API
calls, standard logging keys used where possible.
> PP-7063 Remove payload/ full request body logs

- src/main/java/uk/gov/pay/products/resources/ProductResource.java
The update payload sent from consumers doesn't currently store and
secrets but shouldn't log the whole request as it could change in the
future.
> PP-7063 Remove payload from product update

- src/main/java/uk/gov/pay/products/service/ProductFinder.java
- src/test/java/uk/gov/pay/products/service/ProductFinderTest.java
Add a new method to enable ProductFinder to update Product's API key in a database using the given product external id. This will allow the key to be rotated immediately if it is compromised.
> PP-7293: Add a method to update Product's API key

- pom.xml
- src/main/java/uk/gov/pay/products/ProductsApplication.java
- src/main/java/uk/gov/pay/products/client/publicauth/model/CreateApiTokenRequest.java
- src/main/java/uk/gov/pay/products/client/publicauth/model/NewApiTokenFromPublicAuthResponse.java
- src/main/java/uk/gov/pay/products/client/publicauth/model/TokenSource.java
- src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java
- src/main/java/uk/gov/pay/products/exception/FailToGetNewApiTokenException.java
- src/main/java/uk/gov/pay/products/exception/FailToReplaceApiTokenException.java
- src/main/java/uk/gov/pay/products/exception/mapper/FailToGetNewApiTokenExceptionMapper.java
- src/main/java/uk/gov/pay/products/exception/mapper/FailToReplaceApiTokenExceptionMapper.java
- src/main/java/uk/gov/pay/products/service/ProductApiTokenManager.java
- src/main/resources/config/config.yaml
- src/test/java/uk/gov/pay/products/fixtures/ProductEntityFixture.java
- src/test/java/uk/gov/pay/products/service/ProductApiTokenManagerTest.java
- src/test/resources/config/test-it-config.yaml
This change
- adds a new service called Product API Token Manager which is responsible for getting a new API token from Public Auth application and replacing an old API token with a new API token for a specified product.
- introduces two configuration items (`emailAddressForReplacingApiTokens` and `publicAuthUrl`). `emailAddressForReplacingApiTokens` is required for identifying who makes a request for generating a new API token. `publicAuthUrl` is needed by Products application to send a request to Public Auth application for generating a new API token.
- add unit tests to ensure that the service can receive a new API token from the Public Auth application and replace an old API token with a new API token in a database for a given product.
At this moment, Products application is not using …
> PP-7293: Add a service for handling API token for a product

- README.md
- docs/api_specification.md
- src/main/java/uk/gov/pay/products/config/ProductsModule.java
- src/main/java/uk/gov/pay/products/resources/ProductResource.java
- src/test/java/uk/gov/pay/products/infra/DropwizardAppWithPostgresRule.java
- src/test/java/uk/gov/pay/products/resources/IntegrationTest.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java
This pull request has two commits.
1. The first commit adds a new endpoint `v1/api/products/{productId}/regenerate-api-token` to the products resource. It is used to generate a new API token and replaces an old API token with the new token for a product with a specified external id. This endpoint is needed because the API token can be compromised. It also adds integration tests to ensure the the endpoint can return 200 for successfully replacing API token, 500 for failing to replacing it and 404 for the product which does not exist.
2. The second commit adds information about two new environment variables (EMAIL_ADDRESS_FOR_REPLACING_API_TOKENS and PUBLICAUTH_URL) and the new endpoint (/v1/api/products/{productExternalId}/regenerate-api-token) to README and API specification …
> PP-7293: Add an endpoint for replacing an old API token with a new API token for a product

- src/main/java/uk/gov/pay/products/client/RestClientFactory.java
- src/main/java/uk/gov/pay/products/config/RestClientConfiguration.java
- src/test/java/uk/gov/pay/products/client/RestClientFactoryTest.java
- src/test/java/uk/gov/pay/products/client/publicapi/PublicApiRestClientTest.java
Currently, Jersey client has both connectTimeout and readTimeout set to 0 by default. 0 means infinity. When the client sends a request to another application, it waits until it gets a response. If the request is dropped silently by a firewall or it goes missing, the client will wait forever and never log a timeout exception. This change will add both connectTimeout and readTimeout config items to Products application's config file and are set to 50 seconds by default because Nginx's default timeout is 60 seconds and these timeouts need to be less than 60 seconds to allow Products application to send its response before Nginx cuts off. It also updates RestClientFactoryTest to use JUnit5.
No
* Added new API …
> PP-7293: Add connectTimeout and readTimeout to Jersey client

- src/main/java/uk/gov/pay/products/config/RestClientConfiguration.java
This change updates connectTimeout to use 25 seconds as a default value. It is needed because Jersey client takes 100 seconds to timeout after failing to establish a connection and Nginx cuts this connection after 60 seconds. Reducing from 50 seconds to 25 seconds in connectTimeout causes the timeout to drop from 100 seconds to 50 seconds. readTimeout is not affected by this issue.
I have tested these changes locally.
> PP-7293: Reduce connectTimeout to 25 seconds

- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java
- src/main/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidator.java
- src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
- src/test/java/uk/gov/pay/products/validations/ProductsMetadataRequestValidatorTest.java
- add a metadata validator for product create request. this is needed as the requirements slightly differ to when adding metadata for an existing product
> PP-PP-7358 add metadata validator for product create request

- src/main/java/uk/gov/pay/products/exception/mapper/BadPaymentRequestExceptionMapper.java
- src/main/java/uk/gov/pay/products/exception/mapper/MetadataNotFoundExceptionMapper.java
- src/main/java/uk/gov/pay/products/exception/mapper/PaymentCreatorNotFoundExceptionMapper.java
- src/main/java/uk/gov/pay/products/exception/mapper/ProductNotFoundExceptionMapper.java
For exceptions that are mapped to a 4xx response don't log an error so they aren't reported in Sentry
> BAU Don't log errors when 4xx exceptions are thrown

- docs/api_specification.md
- src/main/java/uk/gov/pay/products/persistence/dao/ProductDao.java
- src/main/java/uk/gov/pay/products/resources/ProductResource.java
- src/main/java/uk/gov/pay/products/service/ProductFinder.java
- src/main/java/uk/gov/pay/products/validations/ProductRequestValidator.java
- src/main/java/uk/gov/pay/products/validations/RequestValidations.java
- src/test/java/uk/gov/pay/products/persistence/dao/ProductDaoIT.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java
- src/test/java/uk/gov/pay/products/service/ProductFinderTest.java
- src/test/java/uk/gov/pay/products/validations/ProductRequestValidatorTest.java
Enhance the `/gateway-account/{gatewayAccountId}/products` endpoint so that it takes an optional `type` parameter with a single value like `ADHOC` or `PROTOTYPE` and filters the results appropriately.
> PP-7709 Allow products to be retrieved by account ID and type

- README.md
Update `README.md` to reference the Cabinet Office CDIO Cyber Security vulnerability disclosure policy and security.txt file rather than the GOV.UK Pay security vulnerability email address.
>  PP-8095 Update vulnerability disclosure in README.md

- pom.xml
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/main/java/uk/gov/pay/products/validations/PanDetector.java
- src/test/java/uk/gov/pay/products/validations/PanDetectorTest.java
Log when we see suspected PAN in reference field. This will enable us to remove `reference` from logs whilst still catching the case when users do this. Products does not log the reference field at all, but once we have this in place can remove the logging from publicapi and connector.
I have chosen to implement this in a separate class to make it easily testable. I have put it in the validator package which is a bit loose, but seems best place for it (happy to discuss this). 
For the actual criteria for "looking like a PAN" I have copied and improved on what we do in frontend [here](https://github.com/alphagov/pay-frontend/blob/437a67cb8c50a9368bb767d9c6b2ca5ce4dee784/app/utils/charge-validation-fields.js#L145) and [here](https://github.com/alphagov/pay-frontend/blob/437a67cb8c50a9368bb76 …
> PP-8415 Detect and log PAN in reference field

- src/test/java/uk/gov/pay/products/pact/ProductsUIContractTest.java
- src/test/java/uk/gov/pay/products/pact/SelfServiceContractTest.java
The purpose of running the provider contract test is to ensure the app can be
deployed to the test environment without breaking its contractual obligations
with other apps. Pacts are tagged with 'test-fargate' in the concourse deploy
pipeline for app deployments so this tag needs to be updated.
> bau: Use 'test-fargate' when running provider contract test

- .github/workflows/_run-pact-provider-tests.yml
Add reusable workflow for products-as-provider pact tests. This is the same code as in adminusers, connector, and ledger but for products
- See the test workflow in frontend https://github.com/alphagov/pay-frontend/runs/5536224723?check_suite_focus=true (this sets the consumer as products-ui, not frontend, but frontend is the only repo set up so far to be able to execute these and with the pact secrets)
N/A
N/A
> PP-9379: Add products as provider pact test reusable workflow

- src/main/resources/migrations/00040_add_column_new_payment_link_journey_enabled_to_products.sql
Add new_payment_link_journey enabled flag to products table. This will be used for enabling the new journey for individual payment links for testing purposes before it is released for all payment links.
> PP-8973 Add flag to enable new payment link journey to products

- .github/workflows/_run-pact-provider-tests.yml
Ensures this reusable workflow takes the HEAD commit of this repo as the provider SHA, rather than the repo calling this workflow.
See equivalent PR for adminusers: https://github.com/alphagov/pay-adminusers/pull/1291
> BAU: Fix Pact Provider version SHA

- src/main/java/uk/gov/pay/products/exception/PaymentCreationException.java
- src/main/java/uk/gov/pay/products/exception/PublicApiResponseErrorException.java
- src/main/java/uk/gov/pay/products/exception/mapper/PaymentCreationExceptionMapper.java
- src/main/java/uk/gov/pay/products/persistence/entity/PaymentEntity.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceIT.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
Public API will respond with a 403 status code either if the gateway account does not have PSP credentials configured or if the gateway account has been disabled.
Pass this status code on in the response for the create payment API in products so that this status code can be used by products-ui to display a more specific error message.
> PP-9587 Pass on 403 status from Public api

- .github/dependabot.yml
- pom.xml
- The Github UI is giving critical warnings for our Java apps with liquibase below v4.8.0. Patched liquibase to 4.12.0
> PP-9620 update liquibase

- src/main/resources/migrations/00044_update_reference_number_in_payments_to_varchar255.sql
Change the type of the `reference_number` column in the `payments` table from `VARCHAR(50`) to `VARCHAR(255)`, which matches what we allow for references for payments elsewhere.
Since PostgreSQL 9.2, increasing the limit for a `VARCHAR` no longer requires a table rewrite (see https://www.postgresql.org/docs/9.2/release-9-2.html#AEN114949) so this migration should be safe.
> PP-6213 Make reference_number in payments table to VARCHAR(255)

- .github/workflows/_run-pact-provider-tests.yml
- .github/workflows/run-tests.yml
- pom.xml
- src/test/java/uk/gov/pay/products/infra/DropwizardAppWithPostgresRule.java
- src/test/java/uk/gov/pay/products/persistence/dao/DaoTestBase.java
- src/test/resources/it-migrations.xml
- removed use of `govuk/postgres:11`, baselining on architecture agnostic `postgres:11.16`
- updated test bases and rules to enable cross architecture support
- added integration tests specific liquibase changelog (`it-migrations.xml`) to initialise the database before migrations can be run
- updated GHA to use new images
> PP-10004 M1 support for integration tests

- openapi/products_spec.yaml
- src/main/java/uk/gov/pay/products/model/Product.java
This field should be included as it is returned in responses.
> BAU Unhide pay_api_token field from OpenApi spec

- .github/workflows/_run-pact-provider-tests.yml
Located and replaced all usages of set-output commands in our workflows.
> PP-10675: replaced usage of set-output in run-pact-provider-tests.yml

- pom.xml
- src/main/java/uk/gov/pay/products/ProductsApplication.java
- src/main/java/uk/gov/pay/products/config/ProductsConfiguration.java
- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
1. Remove graphite metrics configuration and sending
2. Rename GRAPHITE_SENDING_PERIOD_SECONDS to METRICS_COLLECTION_PERIOD_SECONDS, and set it to the appropriate value.
Check build passes and explicitly wait for the e2e tests to pass
* ~Introduced any new environment variables~ / removed existing environment variable
* ~Added new API / updated existing API definition~
> PP-11228: Remove graphite metrics sending and config

- build-local.sh
- src/main/java/uk/gov/pay/products/ProductsApplication.java
Now we don't need to build our default labels in the app (since they are now added by the sidecar) we should remove the default sample builder.
1. Remove default sample builder
2. Update local build script to account for m1 macs, and use the correct container tag
This change has already been rolled out to connector and is working well.
> PP-11154: Update initialise prometheus metrics

- pom.xml
Unlike version 2.7.11, 2.7.13 works with Java 21.
with @SandorArpa
> PP-11652 Upgrade EclipseLink from 2.7.11 to 2.7.13

- src/main/java/uk/gov/pay/products/validations/PaymentRequestValidator.java
- src/main/java/uk/gov/pay/products/validations/RequestValidations.java
- src/test/java/uk/gov/pay/products/validations/PaymentRequestValidatorTest.java
- Updating the payment request validation logic in the PaymentResource.createPayment.
- The PaymentResource.createPayment endpoint  should respond with a meaningfully error message for a £0 prefilled payment link amount. At the moment, a NullPointerException is thrown.
An engineer with experience of the E2E payment journey for prefilled payment link
The error is triggered from the products-ui and a more user friendly message is displayed as propagated from the pay-products API's change
Though, some unit tests were created, manual testing will involve standing up the self service frontend, products-ui and the product api and then simulate the error as per …
> PP-11288-Add-Error-Handling-For-Zero-Amount-Payment-Link

- src/main/java/uk/gov/pay/products/exception/mapper/PaymentCreationExceptionMapper.java
A card number entered in a payment link reference is not something that should be sent to sentry.
> bau: Card number in payment link reference is not an error

- src/main/java/uk/gov/pay/products/util/RandomIdGenerator.java
CodeQL flagged up use of insecure randomness. This shouldn't cause a vulnerability, as it was just used in test code and for generating user reference numbers. Use SecureRandom rather than Random so CodeQL won't raise this again in the future.
> PP-12232 Use SecureRandom

- .github/dependabot.yml
- pom.xml
- src/test/java/uk/gov/pay/products/persistence/dao/ProductMetadataDaoIT.java
Upgrade project to use Guice v6
Remove a test that was breaking with: `IllegalStateException: Requested EntityManager outside work unit. As of Guice 6.0, Guice Persist doesn't automatically begin the unit of work when provisioning an EntityManager.`
This test was NOT testing our code but rather a built in function of com.google.inject.Provider<EntityManager>.
> PP-11723 upgrade guice to v6

- src/main/java/uk/gov/pay/products/exception/mapper/PaymentCreationExceptionMapper.java
- src/main/java/uk/gov/pay/products/util/PublicAPIErrorCodes.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceIT.java
Context: Payment links created from not-yet-configured accounts are causing multiple Sentry alerts. A Zendesk alert is considered preferable
- Handle a misconfigured exception by logging at WARN level rather than as an ERROR
- A splunk alert will be set up to look for these logs and alert Zendesk
> PP-12712 Log misconfigured account error as WARN not ERROR

- src/main/java/uk/gov/pay/products/client/publicapi/PublicApiRestClient.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- If a payment link fails due to a misconfigured account, we want a log at WARN level rather than ERROR, to avoid Sentry noise
- Amend logging statements to WARN if there is an error in the response from publicapi
- A previous PR ensured that the resulting PaymentCreationException will log at WARN level if the cause is a misconfigured account (but did not address the ERROR logs in the create payment process covered here)
- PaymentCreationException will continue to log at ERROR level for other causes of payment creation error
> PP-12712 Log payment creation errors at WARN level

- src/main/java/uk/gov/pay/products/ProductsApplication.java
- src/main/java/uk/gov/pay/products/exception/PaymentCreationException.java
- src/main/java/uk/gov/pay/products/exception/PublicApiResponseErrorException.java
- src/main/java/uk/gov/pay/products/exception/mapper/PaymentCreationExceptionMapper.java
- src/main/java/uk/gov/pay/products/persistence/entity/PaymentEntity.java
- src/main/java/uk/gov/pay/products/service/PaymentCreator.java
- src/main/java/uk/gov/pay/products/util/PublicAPIErrorCodes.java
- src/test/java/uk/gov/pay/products/extension/ProductsAppWithPostgresExtension.java
- src/test/java/uk/gov/pay/products/resources/CreatePaymentResourceIT.java
- src/test/java/uk/gov/pay/products/resources/PaymentResourceIT.java
- src/test/java/uk/gov/pay/products/service/PaymentCreatorTest.java
- src/test/java/uk/gov/pay/products/stubs/publicapi/PublicApiStub.java
When creating a payment against publicapi and there is an issue with the amount - i.e. cannot be zero or cannot be less than 30p where a service uses Stripe - publicapi responds with a 422 and an error body:
```
{
"field": "amount",
"code": "P0102",
"description": "Invalid attribute value: amount. Must be greater than or equal to 1. Refer to https://docs.payments.service.gov.uk/making_payments/#amount" // or "Invalid attribute value: amount. Must be greater than or equal to 30. Refer to https://docs.payments.service.gov.uk/making_payments/#amount"
}
```
For these validation errors, in response to a `POST /v1/api/products/{productExternalId}/payments`, the products app should return a 422 status code with the body
```
{
"errors": [
"Upstream system error."
],
"error_identifier": …
```
> PP-13511: Deal with amount errors when creating a payment

- openapi/products_spec.yaml
- src/main/java/uk/gov/pay/products/model/Product.java
- src/main/java/uk/gov/pay/products/persistence/entity/ProductEntity.java
- src/test/java/uk/gov/pay/products/resources/ProductResourceIT.java
- src/test/java/uk/gov/pay/products/utils/DatabaseTestHelper.java
- add created date (timestamp) to product response 
- create at least two payment links locally 
- view the links in self-service using https://github.com/alphagov/pay-selfservice/pull/4684 
- the most recent payment link you created should be displayed at the top of the list
> PP-14315 Order payment links by created date

- pom.xml
- src/main/java/uk/gov/pay/products/ProductsApplication.java
- src/main/resources/config/config.yaml
- We can migrate to 4.x now we use Dropwizard 4, which would allow us to remove some custom code.
- import `SentryAppenderFactory` from dropwizard-sentry.
> PP-13991 refactor to use vanilla SentryAppenderFactory

- .github/dependabot.yml
Dropwizard released v5. We don't want to upgrade to this version just yet.
Remove `org.dhatim:dropwizard-sentry` ignore. We are using v4 that comes bundled with Dropwizard 4.
> PP-14550 reconfigure dependabot ignore
